version: '3.3'
services:
  backend:
    container_name: cache-optimization
    image: nmluci/cache-optimization:backend
    build: .
    ports:
      - "5000:1972"
  cache_redis:
    container_name: cache_redis
    image: redis:7.0.4
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3001:6379"
    volumes:
      - cache_data:/data
  db_maria:
    image: mariadb:10.8.3
    container_name: db_maria
    environment:
      - MARIADB_ROOT_USERNAME=root
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=stellar_db
    ports:
      - "3003:3306"
    restart: unless-stopped
    volumes:
      - mariadb_data:/data
volumes:
  cache_data: {}
  mariadb_data: {}
    